import _ from "lodash";
import { Collection, StrictLink, LooseLink } from "./Types";

export const unique = true;
export const encrypted = true;
export const required = true;

export const DEFAULT = 0;
export const ON_CREATE = 1;
export const ON_UPDATE = 2;
export const autoGenerated = [DEFAULT];

export const TYPES = {
  //   JavaScript Types || DynamoDB Types
  ARRAY: { name: "Array", dbType: "L" }, //List
  BOOLEAN: { name: "Boolean", dbType: "BOOL" },
  BINARY: { name: "Binary", dbType: "B" },
  DATE: { name: "Date", dbNdbTypeame: "N" },
  FUNCTION: { name: "Function", dbType: "NULL" }, //Functions can't Be stored
  JSON: { name: "Object", dbType: "M" },
  NUMBER: { name: "Number", dbType: "N" },
  REGEXP: { name: "RegExp", dbType: "S" },
  STRING: { name: "String", dbType: "S" },
  SET: { name: "Set", dbType: "SS" },
  //Association Groupings
  STRICT_LINK: new StrictLink(null, false),
  LOOSE_LINK: new LooseLink(null, false),
  COLLECTION: new Collection(),
};
export const CONNECTION_LIST = [
  TYPES.STRICT_LINK.constructor.name,
  TYPES.LOOSE_LINK.constructor.name,
  TYPES.COLLECTION.constructor.name,
];

export const createStrictLink = (foriegnModel, other) => {
  return { type: new StrictLink(foriegnModel), ...other };
};

export const createLooseLink = (foriegnModel, other) => {
  return { type: new LooseLink(foriegnModel), ...other };
};

export const createCollection = (foriegnModel, other) => {
  return { type: new Collection(foriegnModel), ...other };
};

/**
 *
 */
export const typeGn = (type = TYPES.STRING, autoGenerated = [DEFAULT]) => {
  return { type, autoGenerated };
};

/**
 * Props
 */
export const createdDate = typeGn(TYPES.DATE, [ON_CREATE]);
export const updatedDate = typeGn(TYPES.DATE, [ON_UPDATE, ON_CREATE]);
export const id = { ...typeGn(TYPES.STRING, [ON_CREATE]), required, unique };

export default { createdDate, updatedDate, id };
